homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_alt
  unit_system: metric
  time_zone: Europe/Prague
  customize: !include customize.yaml

frontend:

config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:
  include_used_components: true

discovery:
  ignore:
  - google_cast

conversation:

history:
  exclude:
    domains:
    - automation
    - script

logbook:

sun:

sensor:
    - platform: yr
    
    - platform: mqtt
      name: "room1_table_lamp_energy_today"
      state_topic: "tele/sonoff/SENSOR"
      value_template: ' {{ value_json["ENERGY"]["Today"] }}'
      unit_of_measurement: "kWh"
    - platform: mqtt
      name: "room1_table_lamp_energy_yesterday"
      state_topic: "tele/sonoff/SENSOR"
      value_template: ' {{ value_json["ENERGY"]["Yesterday"] }}'
      unit_of_measurement: "kWh"
    - platform: mqtt
      name: "room1_table_lamp_energy_total"
      state_topic: "tele/sonoff/SENSOR"
      value_template: ' {{ value_json["ENERGY"]["Total"] }}'
      unit_of_measurement: "kWh"
    - platform: mqtt
      name: "room1_table_lamp_energy_power"
      state_topic: "tele/sonoff/SENSOR"
      value_template: ' {{ value_json["ENERGY"]["Power"] }}'
      unit_of_measurement: "W"
    - platform: mqtt
      name: "room1_table_lamp_energy_voltage"
      state_topic: "tele/sonoff/SENSOR"
      value_template: ' {{ value_json["ENERGY"]["Voltage"] }}'
      unit_of_measurement: "V"
    - platform: mqtt
      name: "room1_table_lamp_energy_current"
      state_topic: "tele/sonoff/SENSOR"
      value_template: ' {{ value_json["ENERGY"]["Current"] }}'
      unit_of_measurement: "A"

    - platform: mqtt
      name: "room1_table_bme280_temp"
      state_topic: "tele/wemos-d1-mini/SENSOR"
      value_template: ' {{ value_json["BME280"]["Temperature"] }}'
      unit_of_measurement: "°C"
      device_class: temperature
    - platform: mqtt
      name: "room1_table_bme280_humid"
      state_topic: "tele/wemos-d1-mini/SENSOR"
      value_template: ' {{ value_json["BME280"]["Humidity"] }}'
      unit_of_measurement: "%"
      device_class: humidity
    - platform: mqtt
      name: "room1_table_bme280_pressure"
      state_topic: "tele/wemos-d1-mini/SENSOR"
      value_template: ' {{ value_json["BME280"]["Pressure"] }}'
      unit_of_measurement: "hPa"
      device_class: pressure
    - platform: mqtt
      name: "room1_table_sht31_temp"
      state_topic: "tele/wemos-d1-mini/SENSOR"
      value_template: ' {{ value_json["SHT3X-0x44"]["Temperature"] }}'
      unit_of_measurement: "°C"
      device_class: temperature
    - platform: mqtt
      name: "room1_table_sht31_humid"
      state_topic: "tele/wemos-d1-mini/SENSOR"
      value_template: ' {{ value_json["SHT3X-0x44"]["Humidity"] }}'
      unit_of_measurement: "%"
      device_class: humidity      

tts:
  platform: google

group: !include groups.yaml

homekit:
  # nepovinné - pouze pokud provozuje více HomeAssistentů
  name: Homekit Bridge

light:
    - platform: mqtt
      name: "room1_table_lamp"
      state_topic: "stat/sonoff/POWER"    
      command_topic: "cmnd/sonoff/POWER"
      availability_topic: "tele/sonoff/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Aktivní"
      payload_not_available: "Neaktivní"
      retain: false