esphomeyaml:
  name: sonoff_th10
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: 'wifi'
  password: 'wifi_heslo'

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

dallas:
  - pin: GPIO14

sensor:
  - platform: dallas
    address: <VASE_ADRESA_SENSORU>
    name: "Sonoff SH10 Teplota"
    
binary_sensor:
- platform: gpio
  pin:
    number: GPIO0
    mode: INPUT_PULLUP
    inverted: True
  name: "Sonoff TH10 Tlačítko"
  on_press:
    - switch.toggle: relay
- platform: status
  name: "Sonoff TH10 Stav"

switch:
- platform: gpio
  name: "Sonoff TH10 Přepínač"
  pin: GPIO12
  id: relay