esphome:
  name: s55

esp8266:
  board: esp01_1m

# Enable logging
logger:

web_server:
  port: 80
  
# Enable Home Assistant API
api:
  encryption:
    key: "!Secretkey"

ota:
  password: "!otasectret"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "S55 Fallback Hotspot"
    password: "MVt5nqPe74vI"

captive_portal:

#binary_sensor:
#  - platform: gpio
#   pin:
#     number: GPIO0
#      mode:
#        input: true
#        pullup: true
#      inverted: true
#    name: "Power Button"
#    on_press:
#      - switch.toggle: relay

status_led:
  pin:
    number: GPIO13
    inverted: true
    
switch:
  - platform: gpio
    name: "Switch"
    pin: GPIO12
    id: relay
    
dallas:
  - pin: GPIO0

sensor:
  - platform: dallas
    address: 0xe50117b2d9d3ff28
    name: "Current Temperature"
    id: outside_temperature

  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
    
  - platform: uptime
    name: "Device Uptime"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
      
    
