esphome:
  name: bl_gw_01
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_password

esp32_ble_tracker:

sensor:
  - platform: xiaomi_cgd1
    mac_address: '<nahradte mac adresou zarizeni>'
    bindkey: !secret bl_alarm_clock_bind_key
    temperature:
      name: "Xiaomi CGD1 Temperature"
    humidity:
      name: "Xiaomi CGD1 Humidity"
    battery_level:
      name: "Xiaomi CGD1 Battery Level"  

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80       